config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get 'score_information', to: 'pages#score_information'
  get 'materials', to: 'pages#materials'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :garments, only: [ :new, :create, :show, :index, :update ] do
    resources :purchases, only: [ :new ]
    resources :blends, only: [ :new, :create ]

  end

  resources :purchases, only: [ :index, :destroy ]
  resources :materials, only: [ :index, :show ]

end

app/models/garment.rb
class Garment < ApplicationRecord
  belongs_to :brand, optional: true

  has_many :blends
  has_many :materials, through: :blends
  has_one_attached :image
  has_one_attached :tag

#  validates :materials, presence: true
  validate :max_percentage_has_not_been_reached

  accepts_nested_attributes_for :blends, reject_if: :all_blank, allow_destroy: true

  def percentage
    percentages = []
    material = []

    self.materials.each do |m|
        material << m.material_rating
    end

    self.blends.each do |b|
      percentages << b.percentage_material
    end
    rating = percentages.zip(material).map{|x,y| x * y}
    return (rating.sum)/10
  end

  def create_blend(material, garment, percentage_material)
    garment.blends << Blend.new(material: material, percentage_material: percentage_material)
  end



  def tag_text_to_blends
    materials = []
    percentages = []

    composition = self.tag_text.split("%")
    composition.each_with_index do |c, i|
      Material.all.each do |m|
        if c.downcase.include?(m.name.downcase)
          materials << m
        end
      end

      numcap = c.match(/\d+/)
      if !numcap.nil?
        percentages << numcap[0]
      end

    end
    percentages.zip(materials).each do |pct, m| create_blend(m, self, pct)
    end
  end


  def percent_color
      if (self.percentage < 75 && self.percentage >= 50)
        'yellow'
      elsif self.percentage < 50
        'red'
      else
        'green'
      end
  end

  def slogan
    positive_slogan = ['Great choice!', 'GO ECO!', 'Perfect!', 'Go GREEN!', 'Welcome to the ECO club!', 'Small ecological footprint, and a giant leap for mankind!']
    neuteral_slogan = ['I can see you are trying!', 'No one succeeds without effort.', 'You can do anything if you set your mind to it. Keep trying!', 'It does not matter how slowly you go as long as you do not stop.', 'Continue this way to break the ECO barrier in your life']
    negative_slogan = ['Seriously?!', 'Failure is only the opportunity to begin again', 'Maybe you will look for something better?', 'Don\'t tell me you want to buy that..', 'Not approved by ECO team', 'Welcome to the dark side!']
    if percent_color == 'green'
      positive_slogan.sample
    elsif percent_color == 'yellow'
      neuteral_slogan.sample
    else
      negative_slogan.sample
    end
  end

  private

    def max_percentage_has_not_been_reached

      percentage = self.blends.map { |b| b.percentage_material }.compact.sum
      if percentage > 100 || percentage < 100
        errors[:base] << "Total material percentage must be between 0 and 100%"
      end
    end


end

app/controllers/garments_controller.rb
class GarmentsController < ApplicationController

  def new
    @garment = Garment.new
    @garment.blends.build
    @garment.materials.build
    authorize @garment
  end

  def create
    @brand = Brand.new
    @garment = Garment.new(garments_params)
    authorize @garment
    if @garment.blends.length.zero? && !params[:garment][:tag].nil?
      tag_text = RTesseract.new(params[:garment][:tag].tempfile.path).to_s
      @garment.tag_text = tag_text
      @garment.tag_text_to_blends
      render :new
    else
      if @garment.save
        redirect_to garment_path(@garment)
      else params[:garment].nil?
        flash.alert = "Please fill in the form."
        render :new
      end
    end
  end

  def show
    @garment = Garment.find(params[:id])
    authorize @garment
    @garment_rating = @garment.percentage
  end

  def index

  end

  def update
    @garment = Garment.find(params[:id])
    if @garment.update(garments_params)
      @purchase = Purchase.new(garment_id: @garment.id)
      @purchase.user = current_user
      @purchase.save
      redirect_to purchases_path, notice:  "Garment successfully added to closet!"
    else
      flash.alert = "Cannot update"
    end
  end

  private

  def garments_params
    params.require(:garment).permit(:name, :brand_id, :image, :tag, blends_attributes: [:material_id, :percentage_material, :id, :_destroy])
  end

end

app/views/garments/_blend_fields.html.erb
<div class="nested-fields">
  <div class="row div-blend">
    <div class="col-md-6">
      <%= f.association :material, collection: Material.order('name ASC')  %>
    </div>
    <div class="col-md-6">
      <%= f.input :percentage_material, as: :integer %>
    </div>
  </div>
  <%= link_to_remove_association "Remove material", f %>
</div>

app/views/garments/_form_blends.html.erb
  <%= f.simple_fields_for :blends do |blend| %>
    <%= render 'blend_fields', f: blend %>
  <% end %>
  <div class="links">
        <%= link_to_add_association 'Add material', f, :blends %>
  </div>

app/views/garments/_form_image.html.erb
<%= f.input :image, as: :file, label: "Garment Photo" %>
<%= f.input :name, as: :string, label: "Garment name" %>

app/views/garments/_form_other_fields.html.erb
<%= f.input :image, as: :file, label: "Garment Photo" %>
<%= f.input :name, as: :string, label: "Garment name" %>
<%= f.association :brand, collection: Brand.order('name ASC') %>

app/views/garments/new.html.erb
<div class="background-cover">
<div class="container-form mx-auto justify-content-center">
  <div class="row-form justify-content-center">
    <div class="col-md-10 my-auto">
      <div class="bg-light py-3 px-5">
        <div class="">
          <h1 class="text-center">Please enter the clothing information.</h1>
        </div>
        <% flash.each do |type, msg| %>
          <div class="alert alert-info">
            <%= msg %>
          </div>
        <% end %>
        <br>
        <%= simple_form_for (@garment) do |f| %>
          <div class="row justify-content-center">
              <div class="col-md-6">
              <%= f.input :tag, as: :file, label: false %>
              <br>
            </div>
          </div>
          <%= f.button :submit, 'Scan the materials tag', class: "btn btn-dark btn-block" %>
          <br>
          <div class="bg-warning text-center">
            <em> <%= f.error :base %> </em>
          </div>
          <br>
          <div id="revealmanualform">
            <h5 class="text-center">OR manually enter materials & percentages:</h5>
            <br>
          </div>
          <div class="" id="manualform">
            <%= f.simple_fields_for :blends do |blend| %>
              <%= render 'blend_fields', f: blend %>
            <% end %>
            <div class="links">
                  <%= link_to_add_association 'Add material', f, :blends %>
            </div>
          </div>
          <br>
          <%= f.button :submit, 'Calculate the ECO-score!', class: "btn btn-dark btn-block" %>
        <% end %>
        <br>
        <div class="">
          <div class="row mx-auto justify-content-center">
            <div class="m-2">
              <p class="button-label my-0 px-2"><%= link_to purchases_path do %>
                      <i class="fas fa-tshirt"></i>
                    <% end %></p>
                    <span class="button-label-text">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;closet</span>
            </div>
            <div class="m-2">
              <p class="button-label my-0 px-2">  <%= link_to materials_path do %>
                      <i class="fas fa-book-open"></i>
                    <% end %></p>
                <span class="button-label-text">&nbsp;&nbsp;materials</span>
            </div>
         </div>
         </div>
      </div>
    </div>
  </div>
</div>
</div>

app/views/garments/show.html.erb
<div class="background p-3">
  <div class="rating-box col-md-5 container center-align shadow p-5">
    <h4>Your ECO-rating for your garment</h4>
    <p id="slogan"><small> <%= @garment.slogan %> </small></p>
    <div class= "percent d-flex justify-content-around">
      <h1 class= <%= @garment.percent_color %>> <%= link_to "#{@garment_rating}%", score_information_path, class: @garment.percent_color %></h1>
    </div>
    <h5><%= link_to 'Materials', materials_path %></h5>
    <% @garment.blends.each do |blend| %>
    <p class="material"><em><%= blend.percentage_material %>% <%= link_to "#{blend.material.name}", materials_path(anchor: "#{blend.material.name.downcase}")%></em></p>
    <% end %>
    <div class= "ruler d-flex justify-content-around">
      <div class="box">
        <p>0-49</p>
        <p>Not eco recommended</p>
      </div>
      <div class="box">
        <p>50-74</p>
        <p>You can do better!</p>
      </div>
      <div class="box">
        <p>75-100</p>
        <p>Excellent choice!</p>
      </div>
    </div>
    <% if !user_signed_in? || !current_user.purchases.map(&:garment_id).include?(@garment.id)%>
    <br>
    <hr class="solid">
    <p>Do you own this garment? Add to your closet to keep track of your ECO-rating!</p>
         <div class="form-container">
      <%= simple_form_for @garment do |f| %>
        <%= f.input :name, label: "Name of garment" %>
              <div class="">
        <%= f.association :brand, collection: Brand.order('name ASC') %>
          </div>
        <%= f.input :image, as: :file, label: "Image of garment (optional)" %>
      </div>
        <%= f.button :submit, "Add garment to closet", class: "btn btn-dark mt-4" %>
      <% end %>
    <% end %>
    <br>
    <hr class="solid">
  <div class="buttons-container d-flex justify-content-start">
      <div class="buttons-box col">
        <p class="button-icon"><%= link_to '<i class="fas fa-redo-alt"></i>'.html_safe, new_garment_path %></p>
        <p>scan another garment</p>
      </div>
      <div class="buttons-box col">
      <p class="button-icon"><%= link_to '<i class="fas fa-tshirt"></i>'.html_safe, purchases_path %></p>
      <p>closet</p>
      </div>
    </div>

     <p><%= flash[:alert]%></p>

  </div>
</div>