config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get 'score_information', to: 'pages#score_information'
  get 'materials', to: 'pages#materials'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :garments, only: [ :new, :create, :show, :index, :update ] do
    resources :purchases, only: [ :new ]
    resources :blends, only: [ :new, :create ]

  end

  resources :purchases, only: [ :index, :destroy ]
  resources :materials, only: [ :index, :show ]

end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController
    before_action :authenticate_user!

  def new
    @purchase = Purchase.new(garment_id: params[:garment_id])
    garment = current_user.purchases.where(garment_id: params[:garment_id])
    @purchase.user = current_user
    if @purchase.save
      redirect_to purchases_path, notice:  "Garment successfully added to closet!"
    end
  end

  def index
    # @purchases = current_user.purchases - change when sign in works.
    @purchases = Purchase.all
    percentages = @purchases.map {|purchase| purchase.garment.percentage }
    @average = percentages.sum(0.0) / percentages.size
    if (@average < 75 && @average > 50)
      @color = 'yellow'
    elsif @average < 50
      @color = 'red'
    else
      @color = 'green'
    end
  end

  def destroy
    @purchase = Purchase.find(params[:id])
    @purchase.destroy
    redirect_to purchases_path
  end

  private

  def purchases_params
     params.require(:purchase).permit(:garment_id, :user_id)
  end

end

app/views/purchases/index.html.erb
<div class="main-container">
  <div class="title">
    <p><%= flash[:notice]%></p>
    <h1>MY CLOSET <i class="fas fa-seedling"></i>
    </h1>
    <h2>Your total ECO-score is <%= link_to "#{@average.round(1)}%", score_information_path, class: @color %>
      out of <%= @purchases.count %> items.</h2>
      <p><%= link_to "Scan a garment", new_garment_path, class: "btn btn-primary mt-4" %>
      </p>
      <div class="share">
        <p>Share your score</p>
        <div class="links-socialmedia">
          <a href="https://www.instagram.com" target="_blank"><i class="fab fa-instagram"></i></a>
          <a href="https://www.facebook.com" target="_blank"><i class="fab fa-facebook"></i></a>
          <a href="https://twitter.com" target="_blank"><i class="fab fa-twitter"></i></a>
          <a href="https://www.linkedin.com" target="_blank"><i class="fab fa-linkedin"></i></a>
        </div>
      </div>
    </div>
    <div class="container" style="background-image: url('<%= cl_image_path("https://images.unsplash.com/photo-1495195129352-aeb325a55b65?ixlib=rb-1.2.1&auto=format&fit=crop&w=1055&q=80") %>')">
      <div class="cards">
        <% @purchases.reverse.each do |purchase| %>
        <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.2), rgba(0,0,0,0.2)), url('<%= cl_image_path(purchase.purchase_image, width: 300, height: 400, crop: :fill)%>')">
          <%= link_to garment_path(purchase.garment) do %>
          <div class="card-text">
            <div class="card-title">
             <% if !purchase.garment.name.nil?  %>
                <h3><strong><%= purchase.garment.name.capitalize %></strong></h3>
              <% end %>
            </div>
            <div class="card-info-1">
              <p> ECO-rating: <%=purchase.garment.percentage%>%</p>
            </div>
            <div class="card-info-2">
              <% if !purchase.garment.brand.nil?  %>
                <p> Brand: <%= purchase.garment.brand.name %> </p>
              <% end %>
            </div>
            <div class="btn-delete">
              <%= link_to purchase_path(purchase),
              method: :delete,
              data: { confirm: "Delete this item from your closet?" } do %>
              <i class="fas fa-trash"></i>
              <% end %>
            </div>
          </div>
          <% end %>
        </div>
        <% end %>
      </div>
    </div>
  </div>