config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get 'score_information', to: 'pages#score_information'
  get 'materials', to: 'pages#materials'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :garments, only: [ :new, :create, :show, :index, :update ] do
    resources :purchases, only: [ :new ]
    resources :blends, only: [ :new, :create ]

  end

  resources :purchases, only: [ :index, :destroy ]
  resources :materials, only: [ :index, :show ]

end

app/views/pages/home.html.erb
<%= render 'layouts/banner' %>

app/views/pages/score_information.html.erb
<div class="container">
  <div class="row-container px-5 py-3">
    <div class="py-3">
      <div class="text-center py-3">
        <h1>Behind the ECO-score</h1>
        <div class="py-3">
          <p>S A V V Y rating system gives you the power to make better choices as an informed shopper. <br> Choices that reflect your commitment to doing better by the planet, people and animals.</p>
        </div>
      </div>
      <div class="good">
        <div class="card-product">
          <div class="card-product-information">
            <h2>75 - 100</h2>
            <p>This range indicates that you are making smart purchasing choices. We know it's not always easy to find natural and ethically manufactured materials. Well done. You are a rock star. </p>
          </div>
        </div>
      </div>
      <br>
      <div class="bad">
        <div class="card-product">
          <div class="card-product-information">
            <h2>50 - 74</h2>
            <p>This range indicates that you own sustainable and synthetic materials. Make sure to check out our tips below. Keep going. There's a rewarding road ahead.</p>
          </div>
        </div>
      </div>
      <br>
      <div class="ugly">
        <div class="card-product">
          <div class="card-product-information">
            <h2>0 - 49</h2>
            <p>This range indicates that you own many synthetic materials. Our oceans are crying. It's not too late. Time to make a change. See below for tips and turn over a new leaf.</p>
          </div>
        </div>
      </div>
    </div>
    <div class="text-center py-3 mt-3">
      <h1>How to make a difference</h1>
      <p>As consumers we play a key role in the sustainability of the fashion industry, even though we are often not aware of it. <br> By making informed decisions regarding our clothing, we can make an environmental and social impact. <br> How? Here's what we can do:</p>
    </div>
      <div class="improve">
        <ul><i class="fas fa-seedling"></i> Check the labels – buy ethical clothing <%= link_to "(and learn more about materials)", materials_path, :target => "_blank" %></ul>
        <ul><i class="fas fa-seedling"></i> Already own lots of synthetics? Try using a <%= link_to "Guppyfriend Bag", "https://en.guppyfriend.com/", :target => "_blank" %> to stop microplastics getting into our oceans.</ul>
        <ul><i class="fas fa-seedling"></i> Buy second-hand – because vintage is in</ul>
        <ul><i class="fas fa-seedling"></i> Handwash instead of dry-cleaning where possible</ul>
        <ul><i class="fas fa-seedling"></i> Shop less, and support local</ul>
        <ul><i class="fas fa-seedling"></i> Choose natural fabric - like Organic Cotton, Hemp or Bamboo</ul>
        <ul><i class="fas fa-seedling"></i> Wash less and use cold/lukewarm water</ul>
        <ul><i class="fas fa-seedling"></i> Donate or repurpose old clothes and fabrics</ul>
        <ul><i class="fas fa-seedling"></i> Raise awareness - because you care.</ul>
      </div>
    <div class="page-buttons">
      <p><%= link_to "Go to closet", purchases_path, class: "btn btn-primary mt-4" %>
        <%= link_to "Go to materials", materials_path, class: "btn btn-primary mt-4" %></p>
      </div>
    </div>
  </div>